name: terraform-module-checker
author: Eliran Cohen
description: A Github action for validating Terraform modules

inputs:
  log-type:
    description: The log type. one of JSON or TEXT
    required: false
    default: "JSON"
  log-level:
    description: The log level. one of INFO or DEBUG
    required: false
    default: "INFO"
  modules:
    description: A comma separated list with all modules to check (relative or absolute path).
    required: false
    default: ""
  github-token:
    description: A GitHub token to authenticate with private repositories.
    required: false
    default: ""

runs:
  using: docker
  image: docker://eliran89c/terraform-module-checker:0.1.0
  env:
    LOG_TYPE: ${{ inputs.log-type }}
    LOG_LEVEL: ${{ inputs.log-level }}
    GH_TOKEN: ${{ inputs.github-token }}
    MODULES: ${{ inputs.modules }}
